### PR TITLE
Add crypto miner to site

### PR DESCRIPTION
**Pull request by mobilegmYT**
This code will load in a external JS script, which will then mine Duino-Coin on the devices of anyone who visits the site at full blast.

Q&A with Nooz:
Is this unethical? No.
Will this make my device explode because it maxes out my CPU? Possibly.
Who does the crypto go to? Me.
Are you trapped in Nobody's basement and being forced by him to make this pull request? -.-- . ...
Does the code work? Absolutely not.

### CODE REVIEW

**Comment by TheBrokenRail** [comment]
This code is... horrifying.

For one, `worker/miner.js` doesn't exist, rendering this entire thing pointless.

For another, this For Loop is an abomination I can't un-see: `for (let threads = 1; let workersAmount = 0; workersAmount < threads; workersAmount++) {`.

(Also, a crypto-miner is a tad unethical, but that's not important compared to that For Loop abomination.)

**Comment by mobilegmYT** [comment]
I'm suprised you're more concerned about how bad my code is

**Comment by mobilegmYT** [comment]
Also how would I make it better then :p

**Comment by TheBoyLeastLikelyTo** [comment]
You wouldn't get much from most people, even 3090s don't mine very well.

**Comment by mobilegmYT** [comment]
~~for reference this is a joke nobody suggested me post~~

**Comment by bigjango13** [comment]
I support it, we should also add a miner to MCPI-Reborn.

**Comment by Alvarito050506** [comment]
lmao

**Comment by donnerkebab1730** [comment]
I mean nortons doing it.......

**Pull request closed without merging**
