### PR TITLE
SaaS stuff.

### PR DESCRIPTION
**Pull request by nobody5050**
I kinda forgot that this site is built with md, so idk if the webgl to canvas will be possible. Someone will have to tell me how to setup JavaScript on this.

### CODE REVIEW

**Comment by mobilegmYT** [comment]
Well it converts to html after a commit. Maybe find the github actions stuff and make a html fileinstesd of md file

**Comment by nobody5050** [comment]
> Well it converts to html after a commit. Maybe find the github actions stuff and make a html fileinstesd of md file

I’m going to see if GitHub supports mdjs first

**Comment by nobody5050** [comment]
Ok I have a html canvas drawing to the window

**Comment by nobody5050** [comment]
Hm it’s got an error

**Comment by nobody5050** [comment]
You can view the page so far at http://nobody5050.GitHub.Io/mcpi-revival

**Comment by mobilegmYT** [comment]
> You can view the page so far at http://nobody5050.GitHub.Io/mcpi-devs

So does it have any changes with like adding a window or something? The website looks exact same as mcpi.tk

**Comment by nobody5050** [comment]
Yeah click “play mcpi online” underneath the tools divider. It’ll take you to the testing page.

**Comment by Alvarito050506** [comment]
Ohh _progress_

**Comment by nobody5050** [comment]
I’m going to lock comments to collaborators only so that we can keep this more private

**Comment by nobody5050** [comment]
Ok locked to collaborators only

**Comment by nobody5050** [comment]
squash go brr

**Comment by nobody5050** [comment]
~~I commit for like every change haha~~

**Comment by nobody5050** [comment]
Is this still relevant? I know we have mcpi-revival/mcpi-as-a-service now but I’m not sure that’s related to server hosting or if it’s related to actual mcpi as a service

**Comment by Alvarito050506** [comment]
Meh, IDK, I would say it isn't relevant anymore, but I wouldn't close/delete it.

**Comment by mobilegmYT** [comment]
> Alright. I’ll keep it here for another few months until we realize it should have been closed long ago and close it lol

Well uh it's been A month 😉

**Comment by Alvarito050506** [comment]
lol Actually this should be closed.

**Pull request closed without merging**
