### PR TITLE
Start Status Update

### PR DESCRIPTION
**Pull request by TheBrokenRail**
Access At https://thebrokenrail.github.io/mcpi-devs.github.io/

### CODE REVIEW

**Comment by nobody5050** [comment]
update: images look better centered

**Comment by nobody5050** [comment]
Ok both images are now centered

**Comment by mobilegmYT** [comment]
Possibly merge this PR now?

**Comment by mobilegmYT** [comment]
@Alvarito050506 How's the SEO going?

**Comment by mobilegmYT** [comment]
Also at this point, we should just merge this since by the time it gets merged once everything is added, the info will be outdated lol

**Comment by Alvarito050506** [comment]
> How's the SEO going?

Didn't continue it, it's usable and has better Discord integration though.

> Also at this point, we should just merge this since by the time it gets merged once everything is added, the info will be outdated lol

I would say no, since we would confuse people (MCPIL vs MCPIL-R vs gMCPIL/MCPIL.java/MCPIL in HTML).

**Comment by nobody5050** [comment]
> I would say no, since we would confuse people (MCPIL vs MCPIL-R vs gMCPIL/MCPIL.java/MCPIL in HTML).

Still if we don’t complete this soon it won’t be current.

**Comment by Alvarito050506** [comment]
Ok, should we merge?

**Pull request merged**
