### PR TITLE
Broken Link fixes and typo.

### PR DESCRIPTION
**Pull request by leha-code**

### CODE REVIEW

**Comment by mobilegmYT** [comment]
MCPI has a scratch api??

**Comment by leha-code** [comment]
yes. written in python
sorry im not in discord. my pi has gon brick and im trying to fix this

**Comment by mobilegmYT** [comment]
Oh lol. Everything seems good, so I'll merge it,

**Comment by leha-code** [comment]
thanks. still figuring it ll out an finding the problem. my usb ports are not working

**Pull request merged**
